apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-jaeger?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" &&
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/jaeger-all-in-one-pull-request.yaml".pathChanged() ||
      ".tekton/jaeger-all-in-one-push.yaml".pathChanged() ||
      "Dockerfile.allinone".pathChanged() ||
      "jaeger".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: jaeger
    appstudio.openshift.io/component: jaeger-all-in-one
    pipelines.appstudio.openshift.io/type: build
  name: jaeger-all-in-one-on-pull-request
  namespace: rhosdt-tenant
spec:
  taskRunSpecs:
    - pipelineTaskName: prefetch-dependencies
      computeResources:
        requests:
          memory: 3Gi
        limits:
          memory: 4Gi
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "./jaeger"}, {"type": "npm", "path": "./jaeger/jaeger-ui"}]'
  - name: hermetic
    value: "true"
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-all-in-one:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile.allinone
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
  #     - linux/ppc64le
  #     - linux/s390x
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
