apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-jaeger?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    build.appstudio.openshift.io/build-nudge-files: "bundle-patch/update_bundle.sh"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/multi-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/jaeger-agent-pull-request.yaml".pathChanged() ||
      ".tekton/jaeger-agent-push.yaml".pathChanged() ||
      "Dockerfile.agent".pathChanged() ||
      "jaeger".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: jaeger
    appstudio.openshift.io/component: jaeger-agent
    pipelines.appstudio.openshift.io/type: build
  name: jaeger-agent-on-push
  namespace: rhosdt-tenant
spec:
  taskRunSpecs:
    - pipelineTaskName: prefetch-dependencies
      computeResources:
        requests:
          memory: 3Gi
        limits:
          memory: 4Gi
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '[{"type": "gomod", "path": "./jaeger"}]'
  - name: hermetic
    value: "true"
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/jaeger/jaeger-agent:{{revision}}
  - name: dockerfile
    value: Dockerfile.agent
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  - name: build-platforms
    value:
      - localhost
      - linux/arm64
      - linux/ppc64le
      - linux/s390x
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
